# Dependencies
markdown:            kramdown

redcarpet:
  extensions: ["tables", "fenced_code_block"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

exclude:      ["*.Rmd"]

# Setup
title:               The R class
tagline:             'R programming for biologists'
description:         'A course to learn how to develop reproducible and collaborative workflows using R.'
url:                 http://r-bio.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              François Michonneau
  url:               http://francoismichonneau.net
  email:             francois.michonneau@gmail.com

# Custom vars
version:             1.0.0
